# Genetic Algorithm Parameters
POPULATION_SIZE = 50
GENERATIONS = 100
ELITE_COUNT = 5
MUTATION_RATE = 0.1
CROSSOVER_RATE = 0.8

# Neural Network Architecture
NN_INPUT_NODES = 4
NN_HIDDEN_NODES = [6, 4]
NN_OUTPUT_NODES = 1

# Training Parameters
MAX_GAME_TIME = 30000
FITNESS_BONUS_PIPE = 10
FITNESS_BONUS_DISTANCE = 1